name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: List and Read file
          run:
           echo "My first Github Actions Job"
           ls -Itra
           cat README.md


        - name: Generate ASCTI Artwork
          run: cowsay -f dragon "Run for cover,i am a DRAGON....RAWR" >> dragon.txt


        # - name: Read file
        #   run: cat README.md
            

